CREATE TABLE "buildings" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "buildings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"plot_id" bigint NOT NULL,
	"owner_user_id" uuid,
	"building_type" varchar(32) NOT NULL,
	"level" integer DEFAULT 1 NOT NULL,
	"position_x" integer DEFAULT 0 NOT NULL,
	"position_y" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "buildings_plot_position_unique" UNIQUE("plot_id","position_x","position_y"),
	CONSTRAINT "buildings_level_chk" CHECK ("buildings"."level" >= 1)
);
--> statement-breakpoint
CREATE TABLE "plots" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "plots_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"x" integer NOT NULL,
	"y" integer NOT NULL,
	"owner_user_id" uuid,
	"status" varchar(20) DEFAULT 'available' NOT NULL,
	"price" numeric(12, 2) DEFAULT '0' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "plots_coordinates_unique" UNIQUE("x","y"),
	CONSTRAINT "plots_status_chk" CHECK ("plots"."status" in ('available', 'owned', 'locked')),
	CONSTRAINT "plots_price_chk" CHECK ("plots"."price" >= 0)
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"username" varchar(32) NOT NULL,
	"password_hash" varchar(255) NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "users_username_unique" UNIQUE("username"),
	CONSTRAINT "users_username_length_chk" CHECK (char_length("users"."username") between 3 and 32)
);
--> statement-breakpoint
ALTER TABLE "buildings" ADD CONSTRAINT "buildings_plot_id_plots_id_fk" FOREIGN KEY ("plot_id") REFERENCES "public"."plots"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "buildings" ADD CONSTRAINT "buildings_owner_user_id_users_id_fk" FOREIGN KEY ("owner_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "plots" ADD CONSTRAINT "plots_owner_user_id_users_id_fk" FOREIGN KEY ("owner_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_buildings_plot_id" ON "buildings" USING btree ("plot_id");--> statement-breakpoint
CREATE INDEX "idx_buildings_owner_user_id" ON "buildings" USING btree ("owner_user_id");--> statement-breakpoint
CREATE INDEX "idx_buildings_type" ON "buildings" USING btree ("building_type");--> statement-breakpoint
CREATE INDEX "idx_plots_owner_user_id" ON "plots" USING btree ("owner_user_id");--> statement-breakpoint
CREATE INDEX "idx_plots_status" ON "plots" USING btree ("status");